name: Node.js Package

on:
  release:
    types: [created]

jobs:
  # build first to ensure the build is successful before publishing
  # we can also add tests here
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20.6.1'
      - run: npm ci --force
      - run: npm run build

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20.6.1'
          registry-url: https://npm.pkg.github.com/
      - run: npm ci --force
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}